spring.application.name=solus

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/agendplus_db
spring.datasource.username=postgres
spring.datasource.password=ATrick24
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT (adicione no .env ou diretamente)
jwt.secret=zeller_pdv_2026
jwt.expiration=28800000

# Porta do servidor
server.address=0.0.0.0
server.port=8085
spring.jpa.open-in-view=false